"""Domain classification for briefs (marker-based) — PhD-expanded edition.

Expanded with research-level physics markers for QFT, GR, condensed matter,
nuclear/particle physics, and advanced mathematical physics.
"""

from __future__ import annotations

from typing import Literal

Domain = Literal["mathematics", "physics", "chemistry", "pharmacology", "general"]

MATH_BRIEF_MARKERS = (
    # --- Original undergrad markers ---
    "modular",
    "modulo",
    " mod ",
    "divisible",
    "residue",
    "number theory",
    "z_3",
    "z₃",
    "congruence",
    "gcd",
    "prim",
    # --- PhD expansion: algebra / geometry / topology ---
    "cohomology",
    "sheaf",
    "scheme",
    "spectral",
    "hilbert",
    "banach",
    "sobolev",
    "elliptic",
    "mordell",
    "galois",
    "étale",
    "etale",
    "moduli",
    "functor",
    "category",
    "derived",
    "motive",
    "l-adic",
    "p-adic",
    "riemann",
    "zeta",
    "automorphic",
    "langlands",
    "abelian",
    "variety",
    "algebraic",
    "arithmetic",
    "diophantine",
    "transcendental",
    "operator",
    "algebra",
    "homology",
    "homotopy",
    "k-theory",
    "cobordism",
    "morse",
    "floer",
    "gromov",
    "witten",
    "chern",
    "pontryagin",
    "stiefel",
    "whitney",
    "atiyah",
    "singer",
    "grothendieck",
    "topos",
    "stack",
    "gerbe",
    "bundle",
    "characteristic",
    "class",
    "cocycle",
    "coboundary",
    "exact sequence",
    "resolution",
    "projective",
    "injective",
    "flat",
    "smooth",
    "proper",
    "finite",
    "étale",
    "unramified",
    "normal",
    "regular",
    "singular",
    "blowup",
    "desingular",
    "minimal model",
    "mori",
    "canonical",
    "fano",
    "calabi-yau",
    "enriques",
    "k3",
    "abelian",
    "jacobian",
    "picard",
    "brauer",
    "tate",
    "shafarevich",
    "selmer",
    "galois cohomology",
    "class field",
    "iwasawa",
    "langlands",
    # --- PhD expansion: analysis ---
    "sobolev",
    "besov",
    "triebel",
    "hardy",
    "bmo",
    "calderon",
    "zygmund",
    "singular integral",
    "pseudodifferential",
    "fourier integral",
    "wave front",
    "microlocal",
    "distribution",
    "tempered",
    "schwartz",
    "gelfand",
    "shilov",
    "hyperfunction",
    "microfunction",
    "d-module",
    "holonomic",
    "perverse",
    "intersection cohomology",
    "hodge",
    "dolbeault",
    "de rham",
    "laplacian",
    "harmonic",
    "subharmonic",
    "plurisubharmonic",
    "convex",
    "pseudo-convex",
    "stein",
    "oka",
    "cousin",
)

PHYSICS_BRIEF_MARKERS = (
    # --- Original undergrad markers ---
    "stefan",
    "boltzmann",
    "orbit",
    "thermal",
    "radiation",
    "velocity",
    "force",
    "energy",
    "wavelength",
    # --- PhD expansion: quantum field theory ---
    "quantum field",
    "qft",
    "qed",
    "qcd",
    "electroweak",
    "yang-mills",
    "gauge theory",
    "gauge field",
    "gauge group",
    "brst",
    "ghost",
    "faddeev",
    "popov",
    "path integral",
    "feynman",
    "dirac",
    "klein-gordon",
    "proca",
    "majorana",
    "weyl",
    "spinor",
    "helicity",
    "chirality",
    "parity",
    "cp violation",
    "higgs",
    "yukawa",
    "lagrangian",
    "hamiltonian",
    "action",
    "noether",
    "ward",
    "takahashi",
    "slavnov",
    "taylor",
    "renormalization",
    "renormalisation",
    "regularization",
    "dimensional",
    "cutoff",
    "counterterm",
    "beta function",
    "running coupling",
    "asymptotic freedom",
    "confinement",
    "infrared",
    "ultraviolet",
    "divergence",
    "anomaly",
    "instanton",
    "soliton",
    "monopole",
    "vortex",
    "skyrmion",
    "topological",
    "chern-simons",
    "wess-zumino",
    "witten",
    "seiberg",
    # --- PhD expansion: general relativity / gravity ---
    "general relativity",
    "einstein",
    "curvature",
    "ricci",
    "riemann tensor",
    "weyl tensor",
    "geodesic",
    "metric",
    "tetrad",
    "vielbein",
    "spin connection",
    "palatini",
    "cartan",
    "torsion",
    "non-metricity",
    "teleparallel",
    "lorentz",
    "poincaré",
    "diffeomorphism",
    "black hole",
    "schwarzschild",
    "kerr",
    "reissner",
    "nordström",
    "event horizon",
    "singularity",
    "hawking",
    "bekenstein",
    "entropy",
    "holography",
    "ads/cft",
    "anti-de sitter",
    "de sitter",
    "cosmological",
    "friedmann",
    "robertson",
    "walker",
    "inflation",
    "inflaton",
    "dark energy",
    "dark matter",
    "gravitational wave",
    "graviton",
    "quantum gravity",
    "loop quantum",
    "string theory",
    "superstring",
    "brane",
    "m-theory",
    "supergravity",
    "kaluza-klein",
    "compactification",
    "moduli",
    "flux",
    "warped",
    # --- PhD expansion: condensed matter ---
    "condensed matter",
    "superconduct",
    "superfluidity",
    "bose-einstein",
    "fermi",
    "luttinger",
    "landau",
    "ginzburg",
    "anderson",
    "hubbard",
    "heisenberg",
    "ising",
    "xy model",
    "potts",
    "spin glass",
    "frustration",
    "topological order",
    "topological insulator",
    "quantum hall",
    "fractional",
    "anyon",
    "majorana zero",
    "kitaev",
    "toric code",
    "entanglement",
    "spin liquid",
    "mott",
    "charge density wave",
    "spin density",
    "peierls",
    "kondo",
    "heavy fermion",
    "non-fermi",
    "strange metal",
    "pseudogap",
    "criticality",
    "quantum critical",
    "symmetry protected",
    "weyl semimetal",
    "dirac semimetal",
    "topological superconductor",
    # --- PhD expansion: nuclear / particle ---
    "nuclear",
    "hadron",
    "quark",
    "gluon",
    "parton",
    "deep inelastic",
    "structure function",
    "pdf",
    "factorization",
    "collinear",
    "transverse momentum",
    "spin",
    "polarization",
    "fragmentation",
    "jet",
    "particle physics",
    "standard model",
    "ckm",
    "pmns",
    "neutrino",
    "oscillation",
    "seesaw",
    "leptogenesis",
    "baryogenesis",
    "sphaleron",
    "grand unified",
    "gut",
    "proton decay",
    "magnetic monopole",
    "axion",
    "supersymmetry",
    "susy",
    "neutralino",
    "chargino",
    "squark",
    "slepton",
    "r-parity",
    "mssm",
    "nmssm",
    # --- PhD expansion: statistical / thermal ---
    "statistical mechanics",
    "statistical physics",
    "partition function",
    "grand canonical",
    "microcanonical",
    "ergodic",
    "mixing",
    "equilibration",
    "thermalization",
    "eigenstate",
    "eth",
    "otoc",
    "scrambling",
    "butterfly",
    "lyapunov",
    "chaos",
    "integrable",
    "soliton",
    "bethe ansatz",
    "yang-baxter",
    "spin chain",
    "conformal field",
    "cft",
    "vertex operator",
    "kac-moody",
    "virasoro",
    "affine",
    "coset",
    "minimal model",
    "rational",
    "modular",
    "invariant",
    "fusion",
    "braiding",
    "topological",
    # --- PhD expansion: quantum information ---
    "quantum information",
    "quantum computing",
    "qubit",
    "entanglement",
    "bell",
    "ghz",
    "w state",
    "cluster state",
    "graph state",
    "stabilizer",
    "gottesman",
    "knill",
    "surface code",
    "topological",
    "fault-tolerant",
    "threshold",
    "decoherence",
    "quantum error",
    "quantum channel",
    "completely positive",
    "kraus",
    "povm",
    "tomography",
    # --- PhD expansion: optics / photonics ---
    "quantum optics",
    "cavity",
    "qed",
    "jaynes-cummings",
    "rabi",
    "parametric",
    "squeezing",
    "homodyne",
    "heterodyne",
    "hanbury",
    "brown",
    "twiss",
    "photon",
    "entangled photon",
    "spdc",
    "nonlinear optics",
    "kerr",
    "soliton",
    "supercontinuum",
    "frequency comb",
    # --- PhD expansion: plasma / astrophysics ---
    "plasma",
    "magnetohydrodynamic",
    "mhd",
    "alfven",
    "gyrokinetic",
    "vlasov",
    "fokker-planck",
    "tokamak",
    "stellarator",
    "inertial confinement",
    "ignition",
    "breakeven",
    "lawson",
    "astrophysics",
    "stellar",
    "nucleosynthesis",
    "cosmic microwave",
    "cmb",
    "large scale",
    "structure formation",
    "dark matter halo",
    "accretion",
    "agn",
    "gamma ray",
    "x-ray",
    "pulsar",
    "magnetar",
    "supernova",
    "neutron star",
    "white dwarf",
    "chandrasekhar",
)

CHEMISTRY_BRIEF_MARKERS = (
    "polymer",
    "molecule",
    "enzyme",
    "chemical",
    "reaction",
    # --- PhD expansion ---
    "catalyst",
    "catalysis",
    "organometallic",
    "coordination",
    "ligand",
    "synthesis",
    "spectroscopy",
    "nmr",
    "chromatography",
    "electrochemistry",
    "photochemistry",
    "supramolecular",
    "self-assembly",
    "molecular dynamics",
    "density functional",
    "dft",
    "coupled cluster",
    "hartree-fock",
    "post-hartree",
    "basis set",
    "pseudopotential",
    "van der waals",
    "hydrogen bond",
    "hydrophobic",
    "hydrophilic",
    "amphiphilic",
    "surfactant",
    "colloid",
    "nanoparticle",
    "zeolite",
    "metal-organic",
    "mof",
    "covalent organic",
    "cof",
    "perovskite",
    "solid state",
    "crystallography",
    "diffraction",
    "x-ray",
    "rietveld",
    "phase transition",
)

# ─── Undergraduate physics vocabulary ───────────────────────────────────────
# These are common words in undergrad/JEE physics problems that are
# NOT covered by the PhD-level PHYSICS_BRIEF_MARKERS.  Without these,
# briefs like "A ball rolls down a hill..." classify as "general".

PHARMA_BRIEF_MARKERS = (
    "clearance",
    "half-life",
    "half life",
    "pharmacokinetic",
    "pharmacodynamic",
    "bioavailability",
    "dissolution",
    "dose",
    "dosing",
    "enzyme",
    "michaelis",
    "menten",
    "hepatic",
    "renal clearance",
    "absorption",
    "elimination",
    "excretion",
    "metabolism",
    "concentration",
    "plasma",
    "drug",
    "pharmaceutical",
    "toxicology",
    "formulation",
    "therapeutic",
    "qsar",
    "partition coefficient",
    "permeability",
)

UNDERGRAD_PHYSICS_MARKERS = (
    "mass",
    "charge",
    "weight",
    "planet",
    "radius",
    "diameter",
    "pipe",
    "electron",
    "proton",
    "neutron",
    "atom",
    "voltage",
    "current",
    "resistance",
    "capacitor",
    "inductor",
    "magnetic",
    "electric",
    "wave",
    "frequency",
    "amplitude",
    "wavelength",
    "spring",
    "friction",
    "torque",
    "angular",
    "momentum",
    "collision",
    "impulse",
    "power",
    "gravity",
    "orbit",
    "satellite",
    "density",
    "volume",
    "fluid",
    "flow",
    "heat",
    "entropy",
    "engine",
    "efficiency",
    "lens",
    "mirror",
    "reflection",
    "refraction",
    "diffraction",
    "interference",
    "photon",
    "nuclear",
    "decay",
    "half-life",
    "binding",
    "semiconductor",
    "diode",
    "transistor",
    "ball",
    "roll",
    "ramp",
    "pulley",
    "pendulum",
    "projectile",
    "trajectory",
    "kinetic",
    "potential",
    "mechanical",
    "thermal",
    "conductor",
    "insulator",
    "circuit",
    "battery",
    "resistor",
    "switch",
    "transformer",
    "generator",
    "motor",
    "magnet",
    "coil",
    "solenoid",
    "flux",
    "induction",
    "emf",
    "displacement",
    "strain",
    "stress",
    "elastic",
    "plastic",
    "buoyancy",
    "float",
    "sink",
    "archimedes",
    "bernoulli",
    "venturi",
    "hydraulic",
    "pneumatic",
    "oscillation",
    "vibration",
    "damping",
    "resonance",
    "doppler",
    # Fundamental-constant and modern-physics briefs ("What is the speed of
    # light in vacuum?") used to score zero markers and fall to "general"
    # when the embedding model is unavailable. Long, unambiguous tokens only:
    # matching is substring-based, so short stems would false-positive.
    "speed of light",
    "vacuum",
    "relativity",
    "einstein",
    "maxwell",
    "planck",
    "quantum",
    "coulomb",
    "ampere",
    "kelvin",
    "luminosity",
    "sound",
    "ultrasound",
    "pitch",
    "decibel",
    "intensity",
    "illumination",
    "candela",
    "lumen",
    "lux",
    "radiant",
    "emissivity",
    "blackbody",
    "convection",
    "conduction",
    "radiation",
    "adiabatic",
    "isothermal",
    "isobaric",
    "isochoric",
    "carnot",
    "refrigerator",
    "heat pump",
    "spectrum",
    "spectra",
    "emission",
    "absorption",
    "polarization",
    "coherence",
    "laser",
    "hologram",
    "fiber optic",
    "nanometer",
    "angstrom",
    "micrometer",
    "millimeter",
    "centimeter",
    "meter",
    "kilometer",
    "gram",
    "kilogram",
    "newton",
    "pascal",
    "joule",
    "watt",
    "coulomb",
    "volt",
    "ohm",
    "farad",
    "henry",
    "tesla",
    "weber",
    "hertz",
    "acceleration",
    "deceleration",
    "centripetal",
    "centrifugal",
    "coriolis",
    "gyroscope",
    "precession",
    "escape velocity",
    "kepler",
    "copernicus",
    "galileo",
    "newtonian",
    "relativistic",
    "time dilation",
    "length contraction",
    "photoelectric",
    "compton",
    "de broglie",
    "heisenberg",
    "uncertainty",
    "schrodinger",
    "pauli",
    "exclusion",
    "tunneling",
    "fission",
    "fusion",
    "plasma",
    "ionization",
    "isotope",
    "radioactive",
    "alpha particle",
    "beta particle",
    "gamma ray",
    "cosmic ray",
    "x-ray",
    "ultraviolet",
    "infrared",
    "microwave",
    "radio wave",
)


def classify_domain(brief: str, use_ml: bool | None = None) -> Domain:
    """Classify brief domain — ML embedding first, lexical fallback.

    Uses SentenceTransformer embeddings for semantic domain classification.
    Falls back to lexical markers when the model is unavailable or similarity
    is ambiguous (< 0.30 cosine similarity).

    Args:
        use_ml: ``False`` forbids the embedding path outright. Library callers
            need that guarantee: the first ML classification pulls a ~90 MB
            model into the process, which is unacceptable for a call that is
            advertised as taking milliseconds. ``None`` keeps the historical
            behaviour (use the model when it is installed).
    """
    if use_ml is not False:
        try:
            from formulagate.domain_ml import classify_domain_ml
            ml_result = classify_domain_ml(brief)
            if ml_result is not None:
                return ml_result
        except Exception:
            pass  # Fall through to lexical

    # ── Lexical fallback ─────────────────────────────────────────────────
    b = brief.lower()

    # Quick undergrad physics check BEFORE counting full markers
    # (catches "mass", "charge", "temperature", etc. that full markers miss)
    ug_phys_hits = sum(1 for m in UNDERGRAD_PHYSICS_MARKERS if m in b)

    phys_hits = sum(1 for m in PHYSICS_BRIEF_MARKERS if m in b)
    math_hits = sum(1 for m in MATH_BRIEF_MARKERS if m in b)
    chem_hits = sum(1 for m in CHEMISTRY_BRIEF_MARKERS if m in b)
    pharma_hits = sum(1 for m in PHARMA_BRIEF_MARKERS if m in b)

    # Total physics signal = undergrad + PhD markers
    total_phys = phys_hits + ug_phys_hits

    # Pharmacology: check before physics when pharma signal is strong
    if pharma_hits >= 2 and pharma_hits >= total_phys:
        return "pharmacology"
    if pharma_hits >= 3:
        return "pharmacology"

    # Strong physics signal
    if total_phys >= 2:
        return "physics"

    # Physics with weak math
    if total_phys > 0 and total_phys >= math_hits:
        return "physics"

    # Strong math signal
    if math_hits >= 2 and total_phys == 0:
        return "mathematics"

    # Chemistry
    if chem_hits >= 2:
        return "chemistry"

    # Single-marker fallback
    if math_hits > total_phys:
        return "mathematics"
    if total_phys > 0:
        return "physics"
    if chem_hits > 0:
        return "chemistry"

    return "general"